version: '3'

services:
  app:
    volumes:
      - .:/app
      - /app/node_modules
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      NODE_ENV: development
    ports:
      - 5001:5001
    command: npm run start:container

  redis:
    image: redis:5.0.9-alpine
    ports:
      - '6379:6379'
